### ISSUE TITLE
1.18.2 Crash on connect to multiplayer-server

### ISSUE THREAD

**Issue by johannesmateboer** [Kneelawk/WiredRedstone#16] opened 2022-08-26 13:46 UTC
When connecting to a server, the connection is gone and the error in the pastebin is thrown. This only happens when the player is in a chunk with Redstone wires. 

Error: https://pastebin.com/b3niDk3j

**Comment by Kneelawk** [comment] 2022-08-30 09:11
Hi, sorry for the delay.

Does this happen consistently? Do you have any steps to reproduce? This would be helpful information.

From that I'm seeing in the stack-trace, it looks like this *might* be an LNS bug which was fixed in the blanket-con version. Or it *might* be a LMP bug that I've never seen before. Or it *might* be some strange mod interaction. I have never run into this issue myself.

**Comment by johannesmateboer** [comment] 2022-08-30 11:10
I have some more information for you: it has to do with vein-mining, in this case FTB Ultimine. 

I broke a cable with FTB Ultimine, to remove them all at once, and after that the error showed up.

**Comment by Kneelawk** [comment] 2022-08-31 06:26
It seems like something is causing multiparts to attempt to send data before the connection has even opened.

Also, in the text you uploaded to pastebin, it looks like some of the lines have been cut off. Line 6 of the pastebin is actually missing some important information.

**Comment by johannesmateboer** [comment] 2022-08-31 08:51
[2022-08-26-3.log](https://github.com/Kneelawk/WiredRedstone/files/9460081/2022-08-26-3.log)

Here's the complete log, from boot to crash.

**Comment by johannesmateboer** [comment] 2022-09-09 09:31
Update: libmultipart uses version 0.6.0 of LibNetworkStack. 

I've updated it with version 0.6.3 ([download here](https://www.curseforge.com/minecraft/mc-mods/lib-network-stack/files/all?filter-game-version=1738749986%3a73250)) and been testing with it.

Testing for several days now, I didn't get the error again.

**Comment by Kneelawk** [comment] 2022-09-09 10:11
Yeah, that is probably the best option at this point.

The latest version of LMP (which incorporates 0.6.3 of LNS) has a crippling bug in it which prevents wires from functioning properly when first placed. I am waiting for my PR to LMP to be merged and a new release to be made. As soon as that happens, I'll update Wired Redstone to depend on the new LMP version. Though it might make sense for me to just start using a custom LMP version on MC 1.18.2 like I do on MC 1.19.

**Comment by Kneelawk** [comment] 2022-12-06 04:12
This should be fixed in `v0.3.9+1.18.2`. Available on [Modrinth](https://modrinth.com/mod/wiredredstone/version/0.3.9+1.18.2) and [Curseforge](https://www.curseforge.com/minecraft/mc-mods/wired-redstone/files/4136672).

**Closed as completed** 2022-12-06 04:13 UTC
